"""
conversation_handlers.py — Multi-turn Conversation State Machine (v3.0)
========================================================================
Fixes from v2.0:
  1. Auto-reply detection: detect BEFORE sending (exit after 2nd detection, not 3rd)
  2. STOP/hostile handling: detect "STOP", abuse, off-topic — respond once, then end
  3. Intent detection expanded: more Hindi patterns, STOP keyword
  4. Farewell messages are now included in the reply action body (not just rationale)
  5. Auto-reply hook is a strong curiosity hook (not generic)
"""
from __future__ import annotations

import re
import json
import logging
from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime, timezone

log = logging.getLogger("vera.conv")


# ─── State Machine ────────────────────────────────────────────────────────────
class ConvState:
    QUALIFY   = "qualify"
    PITCH     = "pitch"
    ACTION    = "action"
    FOLLOW_UP = "follow_up"
    CLOSED    = "closed"


@dataclass
class ConversationState:
    conversation_id: str
    merchant_id: str
    customer_id: Optional[str] = None
    trigger_id: Optional[str] = None
    state: str = ConvState.PITCH
    history: list[dict] = field(default_factory=list)
    auto_reply_count: int = 0
    turn_count: int = 0
    detected_language: str = "en"
    last_vera_body: str = ""
    merchant_context: Optional[dict] = None
    category_context: Optional[dict] = None
    trigger_context: Optional[dict] = None


# ─── Language detection ───────────────────────────────────────────────────────
HINDI_MARKERS = [
    "haan", "nahi", "kya", "hai", "hoon", "karo", "shukriya",
    "bahut", "theek", "bilkul", "chalega", "zaroor", "mujhe",
    "aapka", "aapki", "mere", "main", "toh", "ki", "ka", "ke",
    "bhi", "agar", "abhi", "phir", "accha", "samajh",
]

def detect_language(message: str) -> str:
    ml = message.lower()
    count = sum(1 for w in HINDI_MARKERS if w in ml)
    return "hi-en" if count >= 2 else "en"


# ─── Auto-reply detection ─────────────────────────────────────────────────────
AUTO_REPLY_SIGNATURES = [
    "thank you for contacting",
    "thank you for reaching out",
    "thanks for contacting",
    "thanks for reaching out",
    "i am currently unavailable",
    "i am not available",
    "currently unavailable",
    "out of office",
    "automated message",
    "automated assistant",
    "automated reply",
    "this is an auto",
    "auto-generated",
    "autogenerated",
    "main ek automated",
    "aapki jaankari ke liye bahut-bahut shukriya",
    "team tak pahuncha",
    "team tak pahuncha deti hoon",
    "will get back to you soon",
    "will get back to you",
    "i will get back",
    "be in touch shortly",
    "business hours",
    "during business hours",
    "we are currently closed",
    "our team will respond",
    "someone will get back",
]

def detect_auto_reply(message: str, history: list[dict]) -> bool:
    """Detect WA Business canned auto-reply."""
    msg_lower = message.lower().strip()

    # Signature match
    for sig in AUTO_REPLY_SIGNATURES:
        if sig in msg_lower:
            return True

    # Verbatim repeat from merchant (same message as their previous message)
    prev_merchant_msgs = [
        t["msg"].strip() for t in history
        if t.get("from") in ("merchant", "customer")
    ]
    if len(prev_merchant_msgs) >= 1 and prev_merchant_msgs[-1] == message.strip():
        return True

    return False


# ─── Intent detection ─────────────────────────────────────────────────────────
ACCEPT_PATTERNS = [
    r"^(yes|yeah|yep|yup|sure|ok|okay|k|done|go|proceed)[.!?,\s]*$",
    r"^(haan|ha|ji haan|theek hai|theek h|chalega|bilkul|zaroor)[.!?,\s]*$",
    r"^yes[,\s]+(send|do|please|book|draft|go|proceed|start|share|show|register|confirm|activate|publish)",
    r"^(haan|ha)\s+(zaroor|bilkul|please|bhai|ji)",
    r"\b(go ahead|let'?s do it|karo|kar do|shuru karo|start karo)\b",
    r"\b(sign me up|join|register|sign up|judrna hai|joinaa hai)\b",
    r"\b(please proceed|please go ahead|yes please|please do it)\b",
    r"\b(sounds good|looks good|perfect|great|awesome|absolutely)\b",
    r"\b(zaroor|bilkul|haan ji|ji zaroor|haan bilkul)\b",
    r"^(send|book|confirm|draft|publish|activate|share|show me)[.!?\s]",
]

REJECT_PATTERNS = [
    r"\b(no|nope|nahi|na|not interested|interested nahi)\b",
    r"\bstop\b",
    r"\b(band karo|mat karo|rehne do|choddo)\b",
    r"\b(later|baad mein|abhi nahi)\b",
    r"\b(busy hoon|time nahi|leave me alone)\b",
    r"\b(unsubscribe|opt out|remove me|block)\b",
    r"\b(don'?t (want|need|care)|not now)\b",
]

HOSTILE_PATTERNS = [
    r"\b(idiot|stupid|useless|waste|scam|fraud|bakwaas|chutiya|gaali)\b",
    r"\b(get lost|go away|shut up|f[*u]ck|damn you)\b",
    r"(gst|income tax|legal|court|police|complaint)",  # off-topic / hostile redirect
]

def detect_intent(message: str) -> str:
    """Returns: accept | reject | hostile | question | neutral"""
    ml = message.lower().strip()

    for pat in HOSTILE_PATTERNS:
        if re.search(pat, ml, re.IGNORECASE):
            return "hostile"

    for pat in REJECT_PATTERNS:
        if re.search(pat, ml, re.IGNORECASE):
            return "reject"

    for pat in ACCEPT_PATTERNS:
        if re.search(pat, ml, re.IGNORECASE):
            return "accept"

    if "?" in message:
        return "question"

    return "neutral"


# ─── Main handler ─────────────────────────────────────────────────────────────
def respond(state: ConversationState, merchant_message: str) -> dict:
    """
    State machine handler for clear-intent messages.
    Called for: auto-reply, accept, reject, hostile.
    """
    # Update language detection
    detected_lang = detect_language(merchant_message)
    if detected_lang == "hi-en":
        state.detected_language = "hi-en"

    is_auto = detect_auto_reply(merchant_message, state.history)
    intent = detect_intent(merchant_message)

    # ── Auto-reply branch ─────────────────────────────────────────────────────
    if is_auto:
        state.auto_reply_count += 1

        if state.auto_reply_count >= 2:
            # ── CRITICAL FIX: Exit after 2nd auto-reply detection (send + end) ──
            farewell = _get_farewell(state, "auto_reply")
            _record_vera(state, farewell)
            state.state = ConvState.CLOSED
            return {
                "action": "end",
                "body": farewell,
                "cta": "none",
                "rationale": f"Auto-reply detected {state.auto_reply_count}× — exiting gracefully",
            }

        # First auto-reply → ONE direct hook (not a generic send)
        hook = _compose_auto_reply_hook(state)
        _record_vera(state, hook)
        return {
            "action": "send",
            "body": hook,
            "cta": "binary_yes_stop",
            "rationale": "Auto-reply detected (count=1) — sending one direct hook to reach real owner",
        }

    # ── Hostile branch ────────────────────────────────────────────────────────
    if intent == "hostile":
        lang = state.detected_language
        merchant = state.merchant_context or {}
        name = merchant.get("identity", {}).get("owner_first_name", "")
        if lang == "hi-en":
            body = f"Koi baat nahi{', ' + name if name else ''} — main yahan hoon jab bhi aap ready hon. 🙏"
        else:
            body = f"No problem{', ' + name if name else ''} — I'm here whenever you need me. Take care! 🙏"
        _record_vera(state, body)
        state.state = ConvState.CLOSED
        return {
            "action": "end",
            "body": body,
            "cta": "none",
            "rationale": "Hostile/off-topic message — exiting gracefully without escalating",
        }

    # ── Reject branch ─────────────────────────────────────────────────────────
    if intent == "reject":
        farewell = _get_farewell(state, "rejected")
        _record_vera(state, farewell)
        state.state = ConvState.CLOSED
        return {
            "action": "end",
            "body": farewell,
            "cta": "none",
            "rationale": "Merchant declined — graceful exit preserves relationship",
        }

    # ── Accept branch ─────────────────────────────────────────────────────────
    if intent == "accept":
        state.state = ConvState.ACTION
        action_msg = _compose_action_response(state, merchant_message)
        _record_vera(state, action_msg)
        return {
            "action": "send",
            "body": action_msg,
            "cta": "open_ended",
            "rationale": "Merchant accepted — transitioned to action mode immediately, no qualifying questions",
        }

    # Fallback for neutral (shouldn't reach here in fast-path, but safety net)
    advance_msg = _compose_advance(state, merchant_message)
    _record_vera(state, advance_msg)
    return {
        "action": "send",
        "body": advance_msg,
        "cta": "binary_yes_stop",
        "rationale": "Neutral response — advancing with new value angle",
    }


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _record_vera(state: ConversationState, body: str):
    state.history.append({"from": "vera", "msg": body, "ts": datetime.now(timezone.utc).isoformat()})
    state.last_vera_body = body


def _get_farewell(state: ConversationState, reason: str) -> str:
    lang = state.detected_language
    merchant = state.merchant_context or {}
    name = merchant.get("identity", {}).get("owner_first_name", "")

    if reason == "auto_reply":
        if lang == "hi-en":
            return f"Koi baat nahi{', ' + name if name else ''} — samajh gayi. Owner se directly connect karti hoon. Best wishes! 🙂"
        return f"Got it{', ' + name if name else ''} — I'll connect with the owner/manager directly. Best wishes! 🙂"
    elif reason == "rejected":
        if lang == "hi-en":
            return f"Bilkul theek hai{', ' + name if name else ''} — jab bhi ready hon, main yahan hoon. 🙏"
        return f"Absolutely fine{', ' + name if name else ''} — whenever you're ready, I'm here. 🙏"
    else:
        if lang == "hi-en":
            return "Theek hai — baad mein baat karte hain. Good luck! 🙂"
        return "No worries — we'll catch up another time. Good luck! 🙂"


def _compose_auto_reply_hook(state: ConversationState) -> str:
    """Strong, data-specific hook to pierce auto-reply and reach the real owner."""
    merchant = state.merchant_context or {}
    category = state.category_context or {}
    lang = state.detected_language
    name = merchant.get("identity", {}).get("owner_first_name", "")
    perf = merchant.get("performance", {})
    peer_stats = category.get("peer_stats", {})
    customer_agg = merchant.get("customer_aggregate", {})
    cat_slug = category.get("slug", "")

    # Use the most compelling data point available
    ctr = perf.get("ctr", 0)
    peer_ctr = peer_stats.get("avg_ctr", 0.03)
    lapsed = customer_agg.get("lapsed_180d_plus", 0)

    prefix = f"Dr. {name}" if cat_slug in ("dentists",) and name else (name or "Hi")

    if lapsed > 10:
        if lang == "hi-en":
            return (
                f"{prefix}, {lapsed} patients 6+ months se wapas nahi aaye — "
                f"main unhe recall message bhej sakti hoon aapki taraf se. "
                f"Typically 20-30% wapas aate hain. Reply YES?"
            )
        return (
            f"{prefix}, {lapsed} of your patients haven't returned in 6+ months — "
            f"I can send them a recall message on your behalf. "
            f"Typically 20-30% come back. Reply YES?"
        )

    if ctr and peer_ctr and ctr < peer_ctr:
        missed = int(perf.get("views", 1000) * (peer_ctr - ctr))
        if lang == "hi-en":
            return (
                f"{prefix}, aapka CTR {int(ctr*100)}% hai vs peers ka {int(peer_ctr*100)}% — "
                f"iska matlab {missed} extra clicks/month chhoot rahe hain. "
                f"Main iska reason diagnose kar sakti hoon. Reply YES?"
            )
        return (
            f"{prefix}, your CTR is {int(ctr*100)}% vs peer avg {int(peer_ctr*100)}% — "
            f"that gap = ~{missed} missed visits/month. "
            f"I can fix this in 10 minutes. Reply YES?"
        )

    # Generic curiosity hook
    if lang == "hi-en":
        return f"{prefix}, ek quick question — is mahine sabse zyada kaunsi service ki demand aa rahi hai? (1 word bhi chalega)"
    return f"{prefix}, quick question — what's your most requested service this month? Even one word helps."


def _compose_action_response(state: ConversationState, merchant_message: str) -> str:
    """Immediate action response when merchant accepts — do the thing, don't ask more questions."""
    merchant = state.merchant_context or {}
    trigger = state.trigger_context or {}
    lang = state.detected_language
    name = merchant.get("identity", {}).get("owner_first_name", "")
    kind = trigger.get("kind", "update")
    cat_slug = (state.category_context or {}).get("slug", "")

    prefix = f"Dr. {name}" if cat_slug in ("dentists",) and name else name

    action_map = {
        "research_digest":         ("pulling the full abstract + drafting a patient-education WhatsApp template", "Drafting now — ready in 30s"),
        "recall_due":              ("booking the slot and sending confirmation to the customer", "Slot confirmed — summary incoming"),
        "perf_dip":                ("running a full profile audit to identify the drop cause", "Audit running — checking 7 factors"),
        "seasonal_perf_dip":       ("analyzing the seasonal pattern and drafting a counter-campaign", "Analysis started"),
        "perf_spike":              ("capturing this momentum — drafting a Google Post + activating offer boost", "Drafting now"),
        "festival_upcoming":       ("drafting a festival campaign with 3 copy variants for your review", "Campaign drafted — sending options"),
        "regulation_change":       ("preparing a compliance checklist tailored to your setup", "Checklist ready in 30s"),
        "dormant_with_vera":       ("picking up your profile optimization from where we left off", "Resuming now"),
        "renewal_due":             ("processing your renewal and confirming the plan", "Renewal confirmed — receipt incoming"),
        "milestone_reached":       ("drafting a milestone post for your Google Business Profile", "Post drafted — want to review?"),
        "competitor_opened":       ("pulling the competitor's full profile for your review", "Analysis ready in 30s"),
        "winback_eligible":        ("activating a win-back campaign for your lapsed customers", "Campaign activated"),
        "supply_alert":            ("preparing a batch recall checklist for your inventory", "Checklist ready"),
        "gbp_unverified":          ("starting the GBP verification walkthrough for you", "Verification steps ready"),
        "cde_opportunity":         ("registering you for the webinar and sending the link", "Registration done — link incoming"),
        "curious_ask_due":         ("noting that and checking if we can feature it", "Got it — checking now"),
        "active_planning_intent":  ("drafting the plan based on your requirements", "Draft ready in 30s"),
        "wedding_package_followup":("drafting the skin prep program details for the customer", "Draft ready"),
        "trial_followup":          ("sending the next session confirmation to the customer", "Confirmation sent"),
        "chronic_refill_due":      ("preparing the refill order for home delivery", "Order queued — confirming details"),
        "category_seasonal":       ("drafting shelf re-arrangement recommendations for the season", "Recommendations ready"),
    }

    action_desc, action_status = action_map.get(kind, ("getting that done for you", "On it"))

    if lang == "hi-en":
        return f"Perfect{', ' + prefix if prefix else ''}! {action_status} — {action_desc.split(' + ')[0]}. Done ✓"
    return f"Perfect{', ' + prefix if prefix else ''}! {action_status} — {action_desc}. Done ✓"


def _compose_question_answer(state: ConversationState, question: str) -> str:
    """Answer merchant's question directly and re-offer value."""
    merchant = state.merchant_context or {}
    category = state.category_context or {}
    lang = state.detected_language
    name = merchant.get("identity", {}).get("owner_first_name", "")
    q_lower = question.lower()

    if any(w in q_lower for w in ["cost", "price", "kitne", "kitna", "charges", "fees", "amount"]):
        if lang == "hi-en":
            return f"Aapke Pro plan mein yeh service included hai — koi extra charge nahi. {name or 'Aap'} chahein toh main full breakdown bhej sakti hoon. Reply YES?"
        return "Under your current Pro plan, this service is included at no extra charge. Want a full breakdown? Reply YES"

    if any(w in q_lower for w in ["time", "kab", "when", "kitne time", "how long", "kitna time"]):
        if lang == "hi-en":
            return "Google pe typically 24-48 ghante mein reflect hota hai. Main progress track karke update karti hoon. Koi aur sawaal?"
        return "Typically reflects on Google within 24-48 hours. I'll track and update you. Any other questions?"

    perf = merchant.get("performance", {})
    peer_stats = category.get("peer_stats", {})
    if perf.get("ctr") and peer_stats.get("avg_ctr"):
        if lang == "hi-en":
            return (
                f"Main aapka Google profile optimize karti hoon — photos, posts, offers, reviews. "
                f"Aapka CTR {int(perf['ctr']*100)}% hai; peers {int(peer_stats['avg_ctr']*100)}% pe hain. "
                f"Main yeh gap close kar sakti hoon. Chalega? Reply YES"
            )
        return (
            f"I optimize your Google Business Profile — photos, posts, offers, reviews. "
            f"Your CTR is {int(perf['ctr']*100)}% vs peer avg {int(peer_stats['avg_ctr']*100)}%. "
            f"I can close that gap. Want me to start? Reply YES"
        )

    if lang == "hi-en":
        return "Samajh gayi — main check karti hoon. Ek second. Kya aap free profile audit chahenge? (FREE, 2 min) Reply YES"
    return "Got it — let me check on that. Want me to run a quick free profile audit while I'm at it? Reply YES"


def _compose_advance(state: ConversationState, merchant_message: str) -> str:
    """Advance with a new angle when merchant is neutral."""
    merchant = state.merchant_context or {}
    category = state.category_context or {}
    lang = state.detected_language
    name = merchant.get("identity", {}).get("owner_first_name", "")
    turn = state.turn_count
    perf = merchant.get("performance", {})
    customer_agg = merchant.get("customer_aggregate", {})
    peer_stats = category.get("peer_stats", {})

    if turn <= 2:
        lapsed = customer_agg.get("lapsed_180d_plus", 0)
        if lapsed > 5:
            if lang == "hi-en":
                return (
                    f"{name or 'Aap'}, aapke {lapsed} customers 6+ months se nahi aaye. "
                    f"Main unhe recall message bhej sakti hoon aapki taraf se — typically 20-30% wapas aate hain. "
                    f"Try karein? Reply YES / STOP"
                )
            return (
                f"{name or 'Quick note'}: {lapsed} of your customers haven't returned in 6+ months. "
                f"I can send them a recall message — typically 20-30% come back. Worth trying? Reply YES / STOP"
            )

    if turn == 3:
        views = perf.get("views", 0)
        ctr = perf.get("ctr", 0)
        peer_ctr = peer_stats.get("avg_ctr", 0.03)
        if views and ctr and ctr < peer_ctr:
            missed = int(views * (peer_ctr - ctr))
            if lang == "hi-en":
                return (
                    f"Last 30 days mein ~{missed} profile visitors convert nahi hue (CTR gap). "
                    f"Main wajah diagnose karke fix kar sakti hoon — 10 min ka kaam. Reply YES?"
                )
            return (
                f"In the last 30 days, ~{missed} profile visitors didn't convert (CTR gap vs peers). "
                f"I can diagnose and fix the reason in 10 minutes. Reply YES?"
            )

    if turn == 4:
        if lang == "hi-en":
            return f"Ek quick question {name or ''}: is mahine kaunsi service ke liye sabse zyada inquiries aa rahi hain? Main uske around ek targeted post draft kar sakti hoon."
        return f"Quick question{', ' + name if name else ''}: what service is getting the most inquiries this month? I'll draft a targeted post around it."

    if lang == "hi-en":
        return "Main aapka Google post already draft kar chuki hoon — sirf approval chahiye. Reply YES aur main publish kar deti hoon. STOP agar interested nahi."
    return "I've already drafted a Google post for you — just need your go-ahead. Reply YES to publish, STOP to skip."
